# 项目相关配置
apm:
  # 名称
  name: APM
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/apm/uploadPath，Linux配置 /home/apm/uploadPath）
  profile: F:/apm/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

#配置端口
server:
  port: 8080

#配置数据库相关信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.132.22.45:3306/apm_vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: admin123
    druid:
      max-active: 10
      min-idle: 5
      max-wait: 50000
      initial-size: 5
      #配置数据源监控信息
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        allow:
        deny:
        url-pattern: "/druid/*"
  redis:
    host: 10.132.22.45 #地址
    port: 6379 #端口
    password:
    timeout: 30000 # 连接超时时间（毫秒）
    database: 1 #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cn.saberking.jvav.apm.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    cn.saberking.jvav.apm: debug

# 指定属性拷贝方式
# 1：Cglib 的 BeanCopier，2：我的，3：带类型转换器的，其他：Spring 的 BeanUtils
bean:
  copy:
    type: 1